export const CREATE_CREDENTIALS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS credentials (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  value TEXT NOT NULL,
  addedAt INTEGER NOT NULL
);
`;

export const CREATE_BREACHES_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS breaches (
  id TEXT PRIMARY KEY,
  credentialId TEXT NOT NULL,
  breachName TEXT NOT NULL,
  date TEXT NOT NULL,
  dataTypes TEXT NOT NULL,
  severity TEXT NOT NULL,
  seen INTEGER DEFAULT 0,
  geminiGuidance TEXT
);
`;

export const CREATE_SEEN_BREACH_IDS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS seen_breach_ids (
  id TEXT PRIMARY KEY
);
`;

export const CREATE_SCAN_RESULTS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS scan_results (
  id TEXT PRIMARY KEY,
  timestamp INTEGER NOT NULL,
  classification TEXT NOT NULL,
  confidence REAL NOT NULL,
  messagePreview TEXT NOT NULL,
  redFlags TEXT NOT NULL,
  suggestedActions TEXT NOT NULL,
  explanation TEXT NOT NULL
);
`;

export const CREATE_WATERMARK_LOG_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS watermark_log (
  id TEXT PRIMARY KEY,
  originalFilename TEXT NOT NULL,
  uuid TEXT NOT NULL,
  timestamp INTEGER NOT NULL
);
`;

export const CREATE_SUGGESTIONS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS suggestions (
  id TEXT PRIMARY KEY,
  scanResultId TEXT,
  action TEXT,
  isActedOn INTEGER DEFAULT 0
);
`;

export const CREATE_SCAN_RESULTS_TIMESTAMP_INDEX_SQL = `
CREATE INDEX IF NOT EXISTS idx_scan_results_timestamp ON scan_results(timestamp);
`;

export const CREATE_BREACHES_CREDENTIAL_INDEX_SQL = `
CREATE INDEX IF NOT EXISTS idx_breaches_credential_id ON breaches(credentialId);
`;

export const DB_INIT_STATEMENTS: string[] = [
  CREATE_CREDENTIALS_TABLE_SQL,
  CREATE_BREACHES_TABLE_SQL,
  CREATE_SEEN_BREACH_IDS_TABLE_SQL,
  CREATE_SCAN_RESULTS_TABLE_SQL,
  CREATE_WATERMARK_LOG_TABLE_SQL,
  CREATE_SUGGESTIONS_TABLE_SQL,
  CREATE_SCAN_RESULTS_TIMESTAMP_INDEX_SQL,
  CREATE_BREACHES_CREDENTIAL_INDEX_SQL,
];